Repository saurabhppawar04/hacktoberfest_2022, pull requests merged in 2022-10, with the labels that each got.

#1 Create insertion_sort.c
  c/sorting/insertion_sort.c
Labels: hacktoberfest-accepted

#2 Create insertion_sort.py
  java/sorting/insertion_sort.java
Labels: enhancement, hacktoberfest-accepted

#3 Create insertion.cpp
  C++/insertion.cpp
Labels: enhancement, hacktoberfest-accepted

#4 Create bubble_sort.c
  c/sorting/bubble_sort.c
Labels: enhancement, hacktoberfest-accepted

#5 added a program for merge sort in C
  c/sorting/merge_sort.c
Labels: enhancement, hacktoberfest-accepted

#6 Create bubble_sort.py
  python/bubble_sort.py
Labels: invalid

#7 Create selection_sort.cpp
  C++/selection_sort.cpp
Labels: enhancement, hacktoberfest-accepted

#8 quick sort
  c/sorting/quicksort.c
Labels: enhancement, hacktoberfest-accepted

#9 Create add_number.c
  c/sorting/add_number.c
Labels: hacktoberfest-accepted

#10 Heap sort code in c
  c/sorting/Heapsort.c
Labels: hacktoberfest-accepted

#11 Create SortStringLexicographically.cpp
  c/sorting/SortStringLexicographically.cpp
Labels: enhancement, hacktoberfest-accepted

#12 Create Sort 0's,1's,2's.cpp
  C++/Sort 0's,1's,2's.cpp
Labels: hacktoberfest-accepted

#13 Create Zip_code.py
  python/Zip_code.py
Labels: hacktoberfest-accepted

#14 Count sort
  c/sorting/countSort.c
Labels: hacktoberfest-accepted

#15 Added 2.Number_Guessing.py
  python/2.Number_Guessing.py
Labels: hacktoberfest-accepted

#16 Added Linear Searching
  C++/linear_searching.cpp
Labels: hacktoberfest-accepted

#17 Make some changes
  README.md
  python/Merge_sort.py
  python/Number_Guessing.py
  python/Quick_sort.py
Labels: hacktoberfest-accepted

#18 Towerofhanoi.cpp
  Towerofhanoi.cpp
Labels: hacktoberfest-accepted

#19 Added code for binary search
  C++/binary_searching.cpp
Labels: hacktoberfest-accepted

#20 Radix Sort using C by Yash Mittal
  radix_sort.c
Labels: hacktoberfest-accepted

#24 floyd warshall
  floyd warshall algorithm dp
Labels: hacktoberfest-accepted

#28 Create Merge_Sort.cpp
  C++/Merge_Sort.cpp
Labels: hacktoberfest-accepted

#26 Solved One problem on recursion
  SumOfNaturalNumber.c
Labels: hacktoberfest-accepted

#30 Create FibonacciSeries.c
  FibonacciSeries.c
Labels: hacktoberfest-accepted

#31 Create string.py
  python/string.py
Labels: hacktoberfest-accepted

#32 Rename factorial.c to c/factorial.c
  c/factorial.c
Labels: hacktoberfest-accepted

#33 Quick_Sort.cpp
  C++/Quick_Sort.cpp
Labels: hacktoberfest-accepted

#34 fibonacci_series.cpp
  C++/fibonacci_series.cpp
Labels: hacktoberfest-accepted

#35 Create cube root of a number
  C++/cube root of a number
Labels: hacktoberfest-accepted

#36 Added Path_Parity.cpp
  C++/Path_Parity.cpp
Labels: hacktoberfest-accepted

#37 Added bankers algorithm in c
  c/bankers_algorithm.c
Labels: hacktoberfest-accepted

#38 Added priority cpu schdeuling
  c/priority.c
Labels: hacktoberfest-accepted

#39 Added a code for circular queue in C language
  c/CircularQueue.c
Labels: hacktoberfest-accepted

#40 circular linked list
  c/circularlinkedlist.c
Labels: hacktoberfest-accepted

#41 Create Prime_Number.cpp
  C++/Prime_Number.cpp
Labels: hacktoberfest-accepted

#43 Create Celsius_to_Fahrenheit.c
  c/Celsius_to_Fahrenheit.c
Labels: hacktoberfest-accepted

#44 Added Linked List Reversal
  java/sorting/LinkedList.java
Labels: hacktoberfest-accepted

#45 Added Algorithms in Respective Folder
  c/AmstrgFrom1ToN.c
  c/ArraySort.c
  c/Bogo Sort.c
  c/EiffelTowerProg.c
  c/Factorial.c
Labels: hacktoberfest-accepted

#46 Create binarysearch.c
  c/binarysearch.c
Labels: hacktoberfest-accepted

#47 Create Leetcode 2. Add Two Numbers
  Leetcode 2. Add Two Numbers
Labels: hacktoberfest-accepted

#48 Create Binary_Search.c
  c/Binary_Search.c
Labels: hacktoberfest-accepted

#49 Create Basic_Calculator.cpp
  C++/Basic_Calculator.cpp
Labels: hacktoberfest-accepted

#50 Add files via upload
  c/Sorting/bubbleSort.c
  c/Sorting/countingSort.c
  c/Sorting/insertionSort.c
Labels: hacktoberfest-accepted

#51 Create InsertionSort.py
  python/InsertionSort.py
Labels: hacktoberfest-accepted

#52 Quick Sort
  Bubble Sort.cpp
  QuickSort.cpp
Labels: hacktoberfest-accepted
